config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resources :users, only: [:edit, :update] do
    collection do
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      put "mypage", :to => "users#update"
    end
  end
  
  resources :touring_logs 
  resources :reviews, only: [:create]
end

app/models/touring_log.rb
class TouringLog < ApplicationRecord
  has_many :reviews, dependent: :destroy

  def reviews_new
     reviews.new
    end

end

app/controllers/touring_logs_controller.rb
class TouringLogsController < ApplicationController
  before_action :set_touring_log, only: [:show, :destroy]
  
  def index
    @touring_logs = TouringLog.all
  end

  def show
    @reviews = @touring_log.reviews
    @review = Review.new
  end

 def new
    @touring_log = TouringLog.new
  end
 
  def create
   @touring_log = TouringLog.new(touring_log_params)
   @touring_log.save
   redirect_to touring_logs_url @touring_log
  end

  def edit
  end

 
  def update
  end

  
  def destroy
    @touring_log.destroy
    redirect_to touring_logs_url
  end

  private

  def set_touring_log
    @touring_log = TouringLog.find(params[:id])
  end


  def touring_log_params
        params.require(:touring_log).permit(:name)
  end  
end

app/helpers/touring_log_helper.rb
module TouringLogHelper
end

app/helpers/touring_logs_helper.rb
module TouringLogsHelper
end

app/views/touring_logs/_form.html.erb
<%= form_with(model: touring_log, local: true) do |form| %>
  <% if touring_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(touring_log.errors.count, "error") %> prohibited this touring_log from being saved:</h2>
      <ul>
      <% touring_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/touring_logs/index.html.erb
<div class="mx-5 my-3">
  <div class="touring_log_title_text">
    <p>〜Touring logs〜</p>
  </div>
  <% @touring_logs.each do |touring_log| %>
    <div class="touring_log_name_title text-center">
      <%= touring_log.name %>
    </div>
    <div class="text-right pr-5 mr-5">
      <%= link_to "コメント", touring_log_path(touring_log) %>
      <%= link_to "削除", touring_log_path(touring_log), method: :delete, data: { confirm: '削除しますか?' }  %>
    </div> 
    <hr>
  <% end %>
  <div class="text-center font-italic  ">
    <%= link_to "New", new_touring_log_path, class: "new_button"  %>
  </div>
</div>

app/views/touring_logs/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Touringlog</title>
  </head>
  <body>
    <div class="container">
      <div class="new_touring_log_title">
        <p>〜New Touring log〜</p>
      </div>
      <%= form_with model: @touring_log do |f| %> 
        <div class="form-group mx-5 bg-dark text-white ">
          <div class="pt-2 pl-3">
            <%= f.label "地名・店舗・施設" %>
          </div>
          <div class="form-style">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="submit-button">
          <%= f.submit "投稿", class:"btn btn-success my-3" %>
        </div>
      <% end %>
      <div class="new_log_return_button">  
        <%= link_to 'Touring logsに戻る', touring_logs_path  %>
      </div>    
    </div>
  </body>
</html> 

app/views/touring_logs/show.html.erb
<div class="py-3 px-5">  
  <div class="comment_page_log_name text-center">
    <%= @touring_log.name %>
  </div>
  <hr>
  <div class="row">
    <% if user_signed_in? %>
      <%= form_with model: @touring_log do |f| %>
        <%= f.hidden_field :id, value: @touring_log.id %>
        <%= f.hidden_field :name, value: @touring_log.name %>  
      <% end %>
    <% end %>
  </div>
  <div class="pt-3 text-center">
    <% @reviews.each do |review| %>
      <div class="offset-mt-5">
        <p class="h3"><%= review.content %></p>
        <label><%= review.created_at %></label>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= form_with model: @touring_log do |f| %>
      <%= f.hidden_field :id, value: @touring_log.id %>
      <%= f.hidden_field :name, value: @touring_log.name %>           
    <% end %>
  <% end %>     
  <div class="offset-md-1 col-md-10 pt-3">
    <%= form_with model: @review, url: reviews_path do |f| %>
      <%= f.hidden_field :touring_log_id, value: @touring_log.id %>
      <div class="font-style offset-1 col-10">
        <%= f.text_area :content, class: "form-control mt-5" %>   
      </div>            
      <div class="ml-5 py-2 text-right">
        <%= f.submit "コメントを追加" , class:"btn touring_log-submit-button ml-2 text-white-50 bg-dark"%>
      </div> 
    <% end %>
    <div class="ml-5 text-right">
      <%= link_to 'Touring logsに戻る', touring_logs_path %> 
    </div>
  </div>
</div>