config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resources :users, only: [:edit, :update] do
    collection do
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      put "mypage", :to => "users#update"
    end
  end
  
  resources :touring_logs 
  resources :reviews, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable #←confirmableを追加
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def verify
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation  ])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :email, :password, :password_confirmation ])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
   verify_path   
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(user)
        touring_logs_path
      end
    
      def after_sign_out_path_for(user)
        root_path
      end
    

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :email, :password, :password_confirmation ])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
    def edit 
    end

    def update
      @user.update(user_params)
      redirect_to mypage_users_url
    end

    def mypage  
    end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.permit(:nickname, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <span>
        <%= link_to "マイページ", mypage_users_path %> > 会員情報の編集
      </span>
      <h1 class="mt-3 mb-3">会員情報の編集</h1>
      <hr>
      <%= form_with url: mypage_users_path, local: true, method: :put do |f| %>
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :nickname, "ニックネーム", class: "text-md-left touring_log-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userName', '.editUserName', '.userNameEditLabel');" class="userNameEditLabel user-edit-label">
            編集
            </span>
          </div>
          <div class="collapse show userName">
            <h1 class="touring_log-edit-user-info-value"><%= @user.nickname %></h1>
          </div>
          <div class="collapse editUserName">
            <%=
              f.text_field :nickname,
              class: "form-control #{"is-invalid" if @user.errors.messages[:name].present? } ",
              value: @user.nickname,
              autofocus: "true",
              required: "",             
              placeholder: "名前を入力"
            %>
            <%= f.submit "保存", class: "btn touring_log-submit-button mt-3 w-25" %>
            <% if @user.errors.messages[:nickname].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>ニックネームを入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>
        <hr>
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :email, "メールアドレス", class: "text-md-left touring_log-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userMail', '.editUserMail', '.userMailEditLabel');" class="userMailEditLabel user-edit-label">
            編集
            </span>
          </div>
          <div class="collapse show userMail">
           <h1 class="touring_log-edit-user-info-value"><%= @user.email %></h1>
          </div>
          <div class="collapse editUserMail">
            <%=
              f.email_field :email,
              class: "form-control #{"is-invalid" if @user.errors.messages[:email].present? }",
              autofocus: "true",
              required: "",
              value: @user.email,
              autocomplete: "email",
              placeholder: "メールアドレスを入力"
            %>
            <%= f.submit "保存", class: "btn touring_log-submit-button mt-3 w-25" %>
            <% if @user.errors.messages[:email].present? %>
              <span class="invalid-feedback" role="alert">
                <strong>メールアドレスを入力してください</strong>
              </span>
            <% end %>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
    let switchEditUserInfo = (textClass, inputClass, labelClass) => {
        if ($(textClass).css('display') == 'block') {
            $(labelClass).text("キャンセル");
            $(textClass).collapse('hide');
            $(inputClass).collapse('show');
        } else {
            $(labelClass).text("編集");
            $(textClass).collapse('show');
            $(inputClass).collapse('hide');
        }
    }
</script>

app/views/users/mypage.html.erb
<div class="container d-flex justify-content-center mt-3 text-cencter">
  <div class="w-50">
    <h1>マイページ</h1>
    <hr>
    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-user fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column ml-1">
              <label for="user-name">アカウント情報の編集</label>             
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center"> 
          <%= link_to mypage_edit_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <div class="container"> 
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-sign-out-alt fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column ml-3">
              <label for="user-name">ログアウト</label>              
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to logout_path, method: :delete do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>