config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resources :users, only: [:edit, :update] do
    collection do
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      put "mypage", :to => "users#update"
    end
  end
  
  resources :touring_logs 
  resources :reviews, only: [:create]
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-bottom mt-5">
  <%= link_to root_path, class: "navbar-brand mx-auto" do %>
  <p>Touring log</p>
  <% end %>
</nav>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm touring_log-header-container">
   <%= link_to root_path do %> 
   <div class="image-size">
    <%= image_tag "/images/logo.jpg" %>
    </div>
   <% end %>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
          <%= link_to mypage_users_path, class: "nav-link" do %>
            <i class="fas fa-user mr-1"></i><label>マイページ</label>
          <% end %>
        </li>  
      <% else %>
        
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <hr>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="far fa-heart"></i><% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="fas fa-shopping-cart"></i><% end %>
        </li>
          <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Touringlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/ea59da4d2d.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
      <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/touringlog.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Touringlog</title>
  </head>
</html>